[project]
name = "dexnet"
version = "0.1.0"

dependencies=[
    "wandb",
    "torchinfo",
    "ruamel.yaml",
    "torch",
    "torchvision",
    "opencv-python",
    "matplotlib",
    "tqdm",
]

[tool.setuptools.packages.find]
include = ["dexnet"]
