[project]
name = "dexnet"
version = "0.1.0"

dependencies=[
    "wandb",
    "torchinfo",
    "ruamel.yaml",
    "torch",
    "torchvision",
    "tyro",
    "opencv-python",
    "matplotlib"
]

[tool.setuptools.packages.find]
include = ["dexnet"]