# config_DexNet.yaml

name: "DexNet3"
optimizer:
  name: "ADAM"
  learning_rate: 0.001
  momentum: .9
  scheduler_gamma: .95
training:
  dataset_path: "dataset/dexnet_3/dexnet_09_13_17"
  batch_size: 256
  num_epochs: 30
  num_files: 2500
  resize: false
outputs:
  save_directory: "outputs/DexNet3"
  save_name: "DexNet3_Adam_train"
  training_print_every: 400
  val_print_every: 1600
  save_every_x_epoch: 10

  

