# Suction training config

name: "DexNet3"
model: "efficientnet"
dataset: "dexnet3"
optimizer:
  name: "adam"
  learning_rate: 0.001
  momentum: .9
  scheduler_gamma: .95   #original is .95, but every .66 epochs. This is per epoch
  weight_decay: 0
training:
  dataset_path: "dataset/dexnet_3/dexnet_09_13_17"
  batch_size: 64
  num_epochs: 25
  resize: false
  GT_threshold: 0.2
  wandb: true
  ordered_split: true
  pos_weight: 1 # make 1 for no oversampling
outputs:
  save_directory: "outputs/efficientnet3"
  save_name: "efficientnet3_v2_s"
  training_print_every: 500
  val_print_every: 2000
  save_every_x_epoch: 5

  

