# Suction training config
name: "DexNet3"
model: "DexNetBase"
dataset: "dexnet3"
optimizer:
  name: "sgd"
  learning_rate: 0.005
  momentum: .9
  scheduler_gamma: .95
  weight_decay: 0.0005
training:
  dataset_path: "dataset/dexnet_3/dexnet_09_13_17"
  batch_size: 256
  num_epochs: 25
  resize: false
  GT_threshold: 0.2 # non-inclusive, label is positive if > GT_threshold
  wandb: true
  ordered_split: true
  pos_weight: 1 # make 1 for no oversampling
outputs:
  save_directory: "outputs/suction_models"
  save_name: "suction_DexNetBase"
  training_print_every: 500
  val_print_every: 2000
  save_every_x_epoch: 10

  

